[package]
name = "subvert"
version = "0.1.0"
authors = ["Johan Geluk <johan@geluk.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "5"